# Generated by Django 3.1.2 on 2021-07-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20000)),
                ('bio', models.CharField(default='', max_length=20000)),
                ('hero', models.CharField(default='', max_length=20000)),
                ('heroin', models.CharField(default='', max_length=20000)),
                ('flix', models.FileField(default='', max_length=5000, upload_to='video/Videos')),
                ('flix_poster', models.ImageField(default='0', upload_to='flix_poster')),
                ('diacter', models.CharField(default='', max_length=20000)),
                ('studio_name', models.CharField(default='', max_length=20000)),
                ('categorys', models.CharField(default='', max_length=20000)),
                ('tags', models.CharField(default='', max_length=20000)),
                ('date_of_relese', models.IntegerField(default='0')),
                ('views', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
