# Generated by Django 3.1.2 on 2021-07-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flix',
            name='flix',
        ),
        migrations.AddField(
            model_name='flix',
            name='Movie',
            field=models.FileField(default='', max_length=5000, upload_to='video/Videos'),
        ),
    ]
